<?php
add_action( 'acf/include_fields', function () {
    if ( !function_exists( 'acf_add_local_field_group' ) ) {
        return;
    }

    acf_add_local_field_group( array(
        'key'                   => 'group_67c6dc68dc231',
        'title'                 => 'Camps de Taxonomies',
        'fields'                => array(
            array(
                'key'                  => 'field_67c6e12371294',
                'label'                => 'Tema',
                'name'                 => 'tema',
                'aria-label'           => '',
                'type'                 => 'taxonomy',
                'instructions'         => '',
                'required'             => 0,
                'conditional_logic'    => 0,
                'wrapper'              => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'taxonomy'             => 'tema',
                'add_term'             => 1,
                'save_terms'           => 1,
                'load_terms'           => 1,
                'return_format'        => 'id',
                'field_type'           => 'checkbox',
                'allow_in_bindings'    => 0,
                'bidirectional'        => 0,
                'multiple'             => 0,
                'allow_null'           => 0,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key'                  => 'field_67c6daed5a3c6',
                'label'                => 'Edat',
                'name'                 => 'edat',
                'aria-label'           => '',
                'type'                 => 'taxonomy',
                'instructions'         => '',
                'required'             => 1,
                'conditional_logic'    => 0,
                'wrapper'              => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'taxonomy'             => 'edat',
                'add_term'             => 1,
                'save_terms'           => 1,
                'load_terms'           => 1,
                'return_format'        => 'id',
                'field_type'           => 'radio',
                'allow_null'           => 0,
                'allow_in_bindings'    => 1,
                'bidirectional'        => 0,
                'multiple'             => 0,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key'                  => 'field_67c6dc69d4063',
                'label'                => 'Àmbit',
                'name'                 => 'ambit',
                'aria-label'           => '',
                'type'                 => 'taxonomy',
                'instructions'         => '',
                'required'             => 0,
                'conditional_logic'    => 0,
                'wrapper'              => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'taxonomy'             => 'ambit',
                'add_term'             => 1,
                'save_terms'           => 1,
                'load_terms'           => 1,
                'return_format'        => 'id',
                'field_type'           => 'checkbox',
                'allow_in_bindings'    => 1,
                'bidirectional'        => 0,
                'multiple'             => 0,
                'allow_null'           => 0,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key'                  => 'field_67c6e8601444f',
                'label'                => 'Etiquetes',
                'name'                 => 'etiquetes',
                'aria-label'           => '',
                'type'                 => 'taxonomy',
                'instructions'         => '',
                'required'             => 0,
                'conditional_logic'    => 0,
                'wrapper'              => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'taxonomy'             => 'etiqueta',
                'add_term'             => 1,
                'save_terms'           => 1,
                'load_terms'           => 1,
                'return_format'        => 'id',
                'field_type'           => 'multi_select',
                'allow_null'           => 0,
                'allow_in_bindings'    => 0,
                'bidirectional'        => 0,
                'multiple'             => 0,
                'bidirectional_target' => array(
                ),
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'recomanacio',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

    acf_add_local_field_group( array(
        'key'                   => 'group_67c5f31275d15',
        'title'                 => 'Camps de Valoracions',
        'fields'                => array(
            array(
                'key'               => 'field_67c5f31323e0a',
                'label'             => 'Lúdic',
                'name'              => 'ludic',
                'aria-label'        => '',
                'type'              => 'range',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => 0,
                'min'               => 0,
                'max'               => 10,
                'allow_in_bindings' => 1,
                'step'              => 2,
                'prepend'           => '',
                'append'            => '',
            ),
            array(
                'key'               => 'field_67c6f099172c1',
                'label'             => 'Cultural',
                'name'              => 'cultural',
                'aria-label'        => '',
                'type'              => 'range',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => 0,
                'min'               => 0,
                'max'               => 10,
                'allow_in_bindings' => 1,
                'step'              => 2,
                'prepend'           => '',
                'append'            => '',
            ),
            array(
                'key'               => 'field_67c6f09a172c2',
                'label'             => 'Educatiu',
                'name'              => 'educatiu',
                'aria-label'        => '',
                'type'              => 'range',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => 0,
                'min'               => 0,
                'max'               => 10,
                'allow_in_bindings' => 1,
                'step'              => 2,
                'prepend'           => '',
                'append'            => '',
            ),
            array(
                'key'               => 'field_67c6f09c172c3',
                'label'             => 'Artístic',
                'name'              => 'artistic',
                'aria-label'        => '',
                'type'              => 'range',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => 0,
                'min'               => 0,
                'max'               => 10,
                'allow_in_bindings' => 1,
                'step'              => 2,
                'prepend'           => '',
                'append'            => '',
            ),
            array(
                'key'               => 'field_67c6d8484fd12',
                'label'             => 'Destacat',
                'name'              => 'destacat',
                'aria-label'        => '',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => 'Recomanació destacada',
                'default_value'     => 0,
                'allow_in_bindings' => 1,
                'ui'                => 0,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'recomanacio',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

    acf_add_local_field_group( array(
        'key'                   => 'group_67c5f2edb57ca',
        'title'                 => 'Camps Generals',
        'fields'                => array(
            array(
                'key'               => 'field_67c5f2ee17fd0',
                'label'             => 'Imatge fons',
                'name'              => 'imatge_fons',
                'aria-label'        => '',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 1,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'array',
                'library'           => 'all',
                'min_width'         => '',
                'min_height'        => '',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
                'allow_in_bindings' => 1,
                'preview_size'      => 'medium',
            ),
            array(
                'key'               => 'field_67c6d82837ff1',
                'label'             => 'Títol',
                'name'              => 'titol',
                'aria-label'        => '',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 1,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'maxlength'         => '',
                'allow_in_bindings' => 0,
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
            ),
            array(
                'key'               => 'field_67c6d83937ff2',
                'label'             => 'Descripció',
                'name'              => 'descripcio',
                'aria-label'        => '',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 1,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'maxlength'         => '',
                'allow_in_bindings' => 0,
                'rows'              => '',
                'placeholder'       => '',
                'new_lines'         => '',
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'recomanacio',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );
} );

add_action( 'init', function () {
    register_taxonomy( 'ambits', array(
        0 => 'recomanacions',
    ), array(
        'labels'       => array(
            'name'                     => 'Àmbits',
            'singular_name'            => 'Àmbit',
            'menu_name'                => 'Àmbit',
            'all_items'                => 'Tots els àmbits',
            'edit_item'                => 'Edita àmbit',
            'view_item'                => 'Veure àmbit',
            'update_item'              => 'Actualitza el nom de l\'àmbit',
            'add_new_item'             => 'Afegir nou àmbit',
            'new_item_name'            => 'Nou nom d\'àmbit',
            'parent_item'              => 'Àmbit pare',
            'parent_item_colon'        => 'Àmbit pare:',
            'search_items'             => 'Cercar àmbits',
            'most_used'                => 'Àmbits més utilitzats',
            'not_found'                => 'Àmbit no trobat',
            'no_terms'                 => 'Sense àmbits',
            'name_field_description'   => 'El \'nom\' és com apareix al lloc web',
            'slug_field_description'   => 'Assigna un \'slug\' per generar la ruta del tema',
            'parent_field_description' => 'Assigna un \'nom-pare\' per generar la jerarquia',
            'desc_field_description'   => 'Assigna una descripció',
            'filter_by_item'           => 'Filtra per àmbit',
            'items_list_navigation'    => 'Navegació per la llista d\'àmbits',
            'items_list'               => 'Llista d\'àmbits',
            'back_to_items'            => 'Tornar a àmbits',
            'item_link'                => 'Enllaç a l\'àmbit',
            'item_link_description'    => 'Un enllaç a l\'àmbit',
        ),
        'description'  => 'Tipus d\'àmbit del recurs àudio visual',
        'public'       => true,
        'hierarchical' => true,
        'show_in_menu' => true,
        'show_in_rest' => true,
        'rewrite'      => array(
            'hierarchical' => true,
        ),
    ) );

    register_taxonomy( 'edats', array(
        0 => 'recomanacions',
    ), array(
        'labels'       => array(
            'name'                     => 'Edats',
            'singular_name'            => 'Edat',
            'menu_name'                => 'Edats',
            'all_items'                => 'Tots Edats',
            'edit_item'                => 'Edita Edat',
            'view_item'                => 'Mostra Edat',
            'update_item'              => 'Actualitza Edat',
            'add_new_item'             => 'Afegeix nou Edat',
            'new_item_name'            => 'Nom de la taxonomia Edat nova',
            'parent_item'              => 'Edat pare',
            'parent_item_colon'        => 'Edat pare:',
            'search_items'             => 'Cerca Edats',
            'most_used'                => 'Edats més utilitzades',
            'not_found'                => 'No s\'han trobat edats',
            'no_terms'                 => 'No hi ha edats',
            'name_field_description'   => 'El \'nom\' és com apareix al lloc web',
            'slug_field_description'   => 'Assigna un \'slug\' per generar la ruta del tema',
            'parent_field_description' => 'Assigna un \'nom-pare\' per generar la jerarquia',
            'desc_field_description'   => 'Assigna una descripció',
            'filter_by_item'           => 'Filtra per edat',
            'items_list_navigation'    => 'Navegació per la lista de Edats',
            'items_list'               => 'Llista de Edats',
            'back_to_items'            => 'Tornar a edats',
            'item_link'                => 'Enllaç a l\'edat',
            'item_link_description'    => 'Un enllaç a l\'edat',
        ),
        'description'  => 'Edat recomanada pel contingut',
        'public'       => true,
        'hierarchical' => true,
        'show_in_menu' => true,
        'show_in_rest' => true,
    ) );

    register_taxonomy( 'etiquetes', array(
        0 => 'recomanacions',
    ), array(
        'labels'       => array(
            'name'                       => 'Etiquetes',
            'singular_name'              => 'Etiqueta',
            'menu_name'                  => 'Etiquetes',
            'all_items'                  => 'Tots Etiquetes',
            'edit_item'                  => 'Edita Etiqueta',
            'view_item'                  => 'Mostra Etiqueta',
            'update_item'                => 'Actualitza Etiqueta',
            'add_new_item'               => 'Afegeix nou Etiqueta',
            'new_item_name'              => 'Nom de la taxonomia Etiqueta nova',
            'search_items'               => 'Cerca Etiquetes',
            'popular_items'              => 'Etiquetes populars',
            'separate_items_with_commas' => 'Separa les etiquetes entre comes',
            'add_or_remove_items'        => 'Afegeix o suprimeix etiquetes',
            'choose_from_most_used'      => 'Tria entre les etiquetes més utilitzades',
            'most_used'                  => 'Més utilitzades',
            'not_found'                  => 'No s\'han trobat etiquetes',
            'no_terms'                   => 'No hi ha etiquetes',
            'name_field_description'     => 'El \'nom\' és com apareix al lloc web',
            'slug_field_description'     => 'Assigna un \'slug\'per generar la ruta del tema',
            'desc_field_description'     => 'Assigna una descripció',
            'items_list_navigation'      => 'Navegació per la lista de Etiquetes',
            'items_list'                 => 'Llista de Etiquetes',
            'back_to_items'              => 'Tornar a etiquetes',
            'item_link'                  => 'Enllaç de Etiqueta',
            'item_link_description'      => 'Un enllaç a etiqueta',
        ),
        'description'  => 'Etiquetes per cada recomanació',
        'public'       => true,
        'show_in_menu' => true,
        'show_in_rest' => true,
    ) );

    register_taxonomy( 'temes', array(
        0 => 'recomanacions',
    ), array(
        'labels'            => array(
            'name'                     => 'Temes',
            'singular_name'            => 'Tema',
            'menu_name'                => 'Tema',
            'all_items'                => 'Tots els temes',
            'edit_item'                => 'Edita tema',
            'view_item'                => 'Veure tema',
            'update_item'              => 'Actualitza el nom del tema',
            'add_new_item'             => 'Afegir nou tema',
            'new_item_name'            => 'Nou nom de tema',
            'parent_item'              => 'Tema pare',
            'parent_item_colon'        => 'Tema pare:',
            'search_items'             => 'Cercar temes',
            'most_used'                => 'Temes més utilitzats',
            'not_found'                => 'Tema no trobat',
            'no_terms'                 => 'Sense tema',
            'name_field_description'   => 'El \'nom\' és com apareix al lloc web',
            'slug_field_description'   => 'Assigna un \'slug\'per generar la ruta del tema',
            'parent_field_description' => 'Assigna un \'nom-pare\' per generar la jerarquia',
            'desc_field_description'   => 'Assigna una descripció',
            'filter_by_item'           => 'Filtra per tema',
            'items_list_navigation'    => 'Navegació per la llista de temes',
            'items_list'               => 'Llista de temes',
            'back_to_items'            => 'Tornar a temes',
            'item_link'                => 'Enllaç al tema',
            'item_link_description'    => 'Un enllaç al tema',
        ),
        'description'       => 'Tipus de temàtica del recurs',
        'public'            => true,
        'hierarchical'      => true,
        'show_in_menu'      => true,
        'show_in_rest'      => true,
        'show_admin_column' => true,
        'rewrite'           => array(
            'hierarchical' => true,
        ),
    ) );
} );

add_action( 'init', function () {
    register_post_type( 'recomanacions', array(
        'labels'           => array(
            'name'                     => 'Recomanacions',
            'singular_name'            => 'Recomanació',
            'menu_name'                => 'Recomanacions',
            'all_items'                => 'Totes les recomanacions',
            'edit_item'                => 'Edita recomanació',
            'view_item'                => 'Veure recomanació',
            'view_items'               => 'Veures recomanacions',
            'add_new_item'             => 'Afegir nova recomanació',
            'add_new'                  => 'Afegir nova',
            'new_item'                 => 'Nova recomanació',
            'parent_item_colon'        => 'Recomanació pare:',
            'search_items'             => 'Cercar recomanació',
            'not_found'                => 'No s\'han trobat recomanacions',
            'not_found_in_trash'       => 'No s\'han trobat recomanacions a la paperera',
            'archives'                 => 'Arxius de recomanació',
            'attributes'               => 'Atributs de recomanació',
            'featured_image'           => 'Imatge destacada de la recomanació',
            'set_featured_image'       => 'Estableix imatge destacada de la recomanació',
            'remove_featured_image'    => 'Elimina imatge destacada de la recomanació',
            'use_featured_image'       => 'Utilitza com a imatge destacada de la recomanació',
            'insert_into_item'         => 'Insereix a la recomanació',
            'uploaded_to_this_item'    => 'Pujat a la recomanació',
            'filter_items_list'        => 'Filtra la llista de recomanacions',
            'items_list_navigation'    => 'Navegació per la llista de recomanacions',
            'items_list'               => 'Llista de recomanacions',
            'item_published'           => 'Recomanació publicada',
            'item_published_privately' => 'Recomanació publicada privadament',
            'item_reverted_to_draft'   => 'Recomanació convertida a esborrany',
            'item_scheduled'           => 'Recomanació agendada',
            'item_updated'             => 'Recomanació actualitzada',
        ),
        'description'      => 'Recomanacions de recursos àudio visuals',
        'public'           => true,
        'show_in_rest'     => true,
        'menu_icon'        => 'dashicons-pressthis',
        'supports'         => false,
        'taxonomies'       => array(
            0 => 'ambits',
            1 => 'edats',
            2 => 'temes',
            3 => 'etiquetes',
        ),
        'has_archive'      => true,
        'rewrite'          => array(
            'feeds' => false,
        ),
        'can_export'       => false,
        'delete_with_user' => false,
    ) );
} );

add_filter( 'enter_title_here', function ( $default, $post ) {
    switch ( $post->post_type ) {
    case 'recomanacions':
        return 'Afegir recomanació';
    }

    return $default;
}, 10, 2 );
